feat: Add logging option to autoRetry function
grammyjs/auto-retry pull request #7
Opened 2023-03-22 20:19 UTC by AbbassAlmusawi

This commit adds a new option to the autoRetry transformer function that enables logging of retry attempts. If the option is set to true, the function will log the retry-after time for each failed request. The option can be passed to the function as a property of the options object.

The logging option is disabled by default, and does not affect the behavior of the function in any way when it is disabled.

Additionally, this commit refactors the code that sets default values for the other options, making it more concise and easier to read.

2023-03-22 22:53 UTC, KnorpelSenf requested changes
Generally, this is a pretty useful addition, thanks!

In production scale applications, using `console.log` is often a too primitive solution. Ideally, this plugin would use the same debug logging that grammY uses ([Deno](https://github.com/grammyjs/grammY/blob/2a894f8dffc9dc1a208cfeb4c1d3553d04ce0f3d/src/platform.deno.ts#L5), [Node](https://github.com/grammyjs/grammY/blob/2a894f8dffc9dc1a208cfeb4c1d3553d04ce0f3d/src/platform.node.ts#L7)). It should then be able to integrate with the custom logger that people use.

How about we do this:
1. By default, always print logs via `debug`. They can be disabled and enabled the same way grammY's logs are managed (via the DEBUG env var).
2. Optionally, let users specify a logger function `(message: string, seconds: number, method: string) => void` that is called. This can be used to rely on the application's logger.

2023-03-22 22:53 UTC, KnorpelSenf commented on src/index.ts
> +                if (logging === true) {
```suggestion
                if (logging) {
```

2023-03-22 22:53 UTC, KnorpelSenf commented on src/index.ts
> +                    console.log(`[${timeString}] Retrying after ${result.parameters.retry_after} seconds`);
We should include in the log message the name of the method which is being called again

2023-03-23 01:03 UTC, AbbassAlmusawi commented
Thanks for the suggestion! I was prefer `console.log` but no problem.  Appreciate the idea of using the debug method for logging.

Therefore, I will remove the "logging" option as it's no longer needed. Additionally, I will remove the if condition that checks if the logger value, since it won't be necessary anymore.

**Q:** I have to edit `package.json` to add `debug` dependency because it exists in grammY `package.json`? and I don't know how to make plug in for Deno! or I don't have to ?

Please let me know if you have any other suggestions or feedback.

2023-03-23 20:31 UTC, wojpawlik submitted a review, later dismissed

2023-03-23 20:31 UTC, wojpawlik commented on src/index.ts
> +                debug(`[${timeString}] Retrying ${method} after ${result.parameters.retry_after} seconds`);
`debug` already adds timing information. Also, "retrying" doesn't make it clear that the call hasn't happened yet.
```suggestion
                debug(`Will retry ${method} after ${result.parameters.retry_after} seconds`);
```

2023-03-23 21:38 UTC, AbbassAlmusawi commented
**Done!** is everything right now?

2023-03-23 21:42 UTC, KnorpelSenf commented
I'll do another review tomorrow or the day after, sorry for the delay

2023-03-24 11:06 UTC, wojpawlik commented
> I don't know how to make plug in for Deno!

Import `debug` from the same place grammY does, (why does grammY miss `?dts` @KnorpelSenf?), and replace `typescript` with `deno2node`.

2023-03-24 12:06 UTC, KnorpelSenf commented
> (why does grammY miss `?dts` @KnorpelSenf?)

What do you mean?

2023-03-26 06:45 UTC, KnorpelSenf commented
This is still on my radar, I just have less time than expected right now

2023-05-20 23:39 UTC, KnorpelSenf commented
I have more time now, so I'll pick this up again soon

2024-01-14 01:14 UTC, KnorpelSenf commented on src/index.ts
> +                debug(`Will retry ${method} after ${result.parameters.retry_after} seconds`);
```suggestion
                debug(`Hit rate limit, will retry '${method}' after ${result.parameters.retry_after} seconds`);
```

2024-01-14 01:14 UTC, KnorpelSenf commented
This clearly got lost, I'm sorry.

2024-01-14 01:15 UTC, KnorpelSenf commented on src/index.ts
> +const debug = d("auto-retry");
```suggestion
const debug = d("grammy:auto-retry");
```

2024-01-14 01:16 UTC, KnorpelSenf approved these changes
I decided to quickly fix up a few details. Thanks for the contribution!

2024-01-14 01:17 UTC, merged