Share retry after across independent execution contexts
grammyjs/auto-retry pull request #9
Opened 2023-06-21 10:26 UTC by KnightNiwrem

If 429 is triggered by some API call in a middleware or some other independent setTimeout call, other async threads that uses the same sessionKey (i.e. bot api token or id) shall also be aware of the recalculated retry_after value.

This attempts to ensure the 429 -> stop all calls until.. -> start sending model.

2023-06-21 10:36 UTC, KnightNiwrem commented on src/index.ts
> +     * Telegram. This is unlike middlewware sessions, which are from user
Typo tsk

2023-06-21 10:58 UTC, KnorpelSenf requested changes
Rate limits are enforced on a per-method basis. They may affect each other indirectly, but we should delay all calls to the same method—not session key.

Amazing work btw!

2023-06-29 15:01 UTC, KnightNiwrem commented
> Rate limits are enforced on a per-method basis. They may affect each other indirectly, but we should delay all calls to the same method—not session key.
> 
> Amazing work btw!

Fixed.. I think?

2024-01-14 01:19 UTC, KnorpelSenf commented
@KnightNiwrem how well did you test this?

2024-03-16 15:28 UTC, KnorpelSenf commented
This is not a good idea. For examples, responses to messages might still be sent while broadcasting is slowed down. It makes sense to keep unrelated API call independent, and not apply rate limits of one call to other calls.

Bot developers need to make sure that they don't call a method too many times concurrently.

2024-03-16 15:28 UTC, closed without merging